### ISSUE TITLE
scrashowany toster

### ISSUE THREAD

**Issue by sznyk5252** [MikolajKolek/toster#25]
Po wpisaniu takiej komendy wyskoczył mi error
toster -i /home/szymek/Desktop/bud/in -o /home/szymek/Desktop/bud/out /home/szymek/Desktop/bud/budowa_lotniska2.cpp
wyskoczył mi error i nie za bardzo wiem co jest nie tak, wiec byłbym wdzięczny za pomoc. Chciałem też wrzucić report file ale github nie pozwala mi wysłać pliku .toml

**Comment by MikolajKolek** [comment]
Możesz po prostu wysłać report file tekstowo, tak jak w #24 na przykład, bez niego nie za wiele mogę pomóc

**Comment by sznyk5252** [comment]
name = "toster"
operating_system = "Ubuntu 22.04 (jammy) [64-bit]"
crate_version = "1.1.4"
explanation = """
Panic occurred in file '/home/szymek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/toster-1.1.4/src/testing_utils.rs' at line 131
"""
cause = "Failed to run file!: Os { code: 8, kind: Uncategorized, message: \"Exec format error\" }"
method = "Panic"
backtrace = """

   0: 0x55b7cac1c1ea - core::result::unwrap_failed::hccb456d39e9c31fc
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652
   1: 0x55b7cac29c2a - toster::testing_utils::generate_output_default::h3d7e170df1632724
   2: 0x55b7cac2a591 - toster::testing_utils::run_test::h2593d81e8895f31e
   3: 0x55b7cac34ede - <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume::h8ac0b12c9f57629f
   4: 0x55b7cac30c4e - rayon::iter::plumbing::bridge_producer_consumer::helper::h0de86b6cc541d3f5
   5: 0x55b7cac361ea - rayon_core::join::join_context::{{closure}}::h7e83d5c3398db41c
   6: 0x55b7cac3652d - rayon_core::registry::in_worker::h901f4f0daa976ba9
   7: 0x55b7cac30d7b - rayon::iter::plumbing::bridge_producer_consumer::helper::h0de86b6cc541d3f5
   8: 0x55b7cac361ea - rayon_core::join::join_context::{{closure}}::h7e83d5c3398db41c
   9: 0x55b7cac3652d - rayon_core::registry::in_worker::h901f4f0daa976ba9
  10: 0x55b7cac30d7b - rayon::iter::plumbing::bridge_producer_consumer::helper::h0de86b6cc541d3f5
  11: 0x55b7cac361ea - rayon_core::join::join_context::{{closure}}::h7e83d5c3398db41c
  12: 0x55b7cac3652d - rayon_core::registry::in_worker::h901f4f0daa976ba9
  13: 0x55b7cac30d7b - rayon::iter::plumbing::bridge_producer_consumer::helper::h0de86b6cc541d3f5
  14: 0x55b7cac37e3d - rayon_core::join::join_context::{{closure}}::h7e83d5c3398db41c
  15: 0x55b7cac3253a - std::panicking::try::h90c1ad9af1a50c67
  16: 0x55b7cac31336 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h7452060d72f516ea
  17: 0x55b7cac1279f - rayon_core::registry::WorkerThread::wait_until_cold::h84205a6383fbd267
  18: 0x55b7cac5de02 - rayon_core::registry::ThreadBuilder::run::h9e23b76877479e83
  19: 0x55b7cac61aca - std::sys_common::backtrace::__rust_begin_short_backtrace::h2b245ab01b8213b7
  20: 0x55b7cac62bcf - core::ops::function::FnOnce::call_once{{vtable.shim}}::h213da4030aec2e80
  21: 0x55b7cad49935 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::haadd4e5af2ab0d62
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007
                 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he4ba1fb09c16d807
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007
                 - std::sys::unix::thread::Thread::new::thread_start::he524ecf4b47bee95
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/unix/thread.rs:108
  22: 0x7f5b49c94ac3 - start_thread
                at ./nptl/pthread_create.c:442
  23: 0x7f5b49d26a40 - clone3
                at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  24:        0x0 - <unresolved>"""

**Comment by sznyk5252** [comment]
Z góry przepraszam za tak wolną odpowiedź

**Comment by MikolajKolek** [comment]
Hm, exec format error by sugerował, że coś się niepoprawnie kompiluje może? Czy jak kompilujesz ręcznie jak w Tosterze przez `g++ -std=c++20 -O3 -static <IN> -o <OUT>` to wszystko działa poprawnie?

**Comment by sznyk5252** [comment]
Wpisałem do kodu na początku cout... żeby wiedzieć czy się skompiluje i coś wypisze, wpisałem g++ -std=c++20 -O3 -static /home/szymek/Desktop/bud/budowa_lotniska2.cpp i nie wyrzuciło żadnego błędu ale też nic nie wypisało do konsoli, ale nie wiem czy dobrze wpisałem bo nie mogłem nigdzie znaleść podobnej komendy. Sprawdziłem czy g++ jest zainstalowane i jest

**Comment by MikolajKolek** [comment]
Musisz uruchomić swój program po tym jak go skompilujesz. Domyślnie, g++ skompiluje ci kod do pliku `a.out`, możesz go uruchomić przez `./a.out`

**Comment by sznyk5252** [comment]
sprawdziłem i wypisał co miał wypisać, wiec się kompiluje

**Comment by MikolajKolek** [comment]
Czy możesz sprawdzić, czy ten błąd występuje też na najnowszej wersji Tostera? Wydaje mi się, że może być spowodowany przez coś co już naprawiłem. Zaktualizować Tostera możesz po prostu przez `cargo install toster`
