### ISSUE TITLE
Your code is terrible, stop writing cpp in rust

### ISSUE THREAD

**Issue by SildCave** [MikolajKolek/toster#36]
Just a pro tip, rust is not cpp. But overall nice checker <3

**Comment by MikolajKolek** [comment]
Well, that's kinda harsh, but also very fair lol. I've never written anything in Rust before and even for those standards the code is absolutely hideous and I'm planning to rewrite large chunks of it once I have the time. If you have any suggestions for how I can apply "rust is not a cpp" and change it for the better, they are most certainly welcome. 
The large chunk of global variables in `main.rs` for example really pains me, but I couldn't figure out a way to get rid of it while keeping the ctrlc feature working, I think maybe it can be done with lifetimes somehow, but the last time I had a look at it I couldn't figure out a way to fix it.

**Comment by SildCave** [comment]
Just don't give up and you will get there
