### ISSUE TITLE
Problem z flagą --sio2jail

### ISSUE THREAD

**Issue by MikorzPL** [MikolajKolek/toster#37]
Gdy próbuję przetestować kod z flagą `--sio2jail`, dostaję komunikat: 
`Sio2jail error: Exception occurred: System error occured: perf event open failed: No such file or directory: error 2: No such file or directory`
Używam tostera na Ubuntu-22.04 na WSL2 na Windowsie 11

**Comment by MikolajKolek** [comment]
Hm, jest to bardzo dziwne, Toster wydaje się działać u mnie pod WSLem bez problemów, ale twój błąd sugerowałby z jakiegoś powodu brak dostępu do liczników sprzętowych. Mógłbyś sprawdzić, czy może działa po wpisaniu `sudo sysctl -w kernel.unpriviledged_userns_clone=1` i jeżeli dalej nie działa podać co ci się wypisuje po `uname -a`?

**Comment by MikorzPL** [comment]
Przy `sudo sysctl -w kernel.unpriviledged_userns_clone=1` wypisuje błąd: `cannot stat/proc/sys/kernel/unpriviledged_userns_clone: No such file or directory`. 
Po wpisaniu `uname -a` wypisuje: `Linux DESKTOP-SLQ9QPG 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by MikolajKolek** [comment]
Używasz ponad dwuletniej wersji WSLa, może w tym leży problem. Wiem, że Microsoft wprowadził od tamtego czasu zmiany co do tych liczników sprzętowych. Spróbuj zrobić `wsl --update` (poza WSLem) i sprawdzić czy tak zadziała, jak nie to podaj co teraz wypisuje ci `uname -a`

**Comment by MikolajKolek** [comment]
Nie ma za co! W następnej wersji Tostera dodam lepszy error handling do tego błędu pod WSLem z instrukcjami jak go rozwiązać, bo obecnie rzeczywiście trudno się domyślić co może być problemem
