### ISSUE TITLE
[feature request] Implement config for number of parallel tasks

### ISSUE THREAD

**Issue by Aldijonas** [MikolajKolek/toster#50]
My CPU can handle more parallel tasks, please implement an option to stress CPU even more during testing. It would make a great difference on testing.

**Comment by MikolajKolek** [comment]
Hm, this is very strange, as Rayon, the library Toster uses to parallelize running tests, is pretty good at fully stressing the CPU, and it spawns as many threads as there are logical cores available. I think you may be facing a different bottleneck (Memory speed or disk I/O perhaps)?

However, you can still try setting the `RAYON_NUM_THREADS` environment variable to a value equal to the number of parallel tasks you want to run and report back if it makes a difference. It should do exactly what you want, and if it does help, I'll eventually implement this directly as a Toster feature.

**Comment by Aldijonas** [comment]
Setting rayon_num_threads to nproc (number of threads in a CPU, in my case 8) did result once in greater, and once in lesser time. It seems to be no difference, or barely any compared to default. Your tool is great as it is, no need to improve parallel task I think.
