### ISSUE TITLE
toster crash report

### ISSUE THREAD

**Issue by Maritsu** [MikolajKolek/toster#51]
submitting as requested. uploading as a .txt file as github won't let me upload .toml files
[report-32be1c8a-731f-486f-b090-e886bbfaaf31.txt](https://github.com/user-attachments/files/17660766/report-32be1c8a-731f-486f-b090-e886bbfaaf31.txt)

**Comment by MikolajKolek** [comment]
This seems to be a problem in Rust versions >=1.81, as the test name sorting library I use doesn't work on those versions anymore. I recommend temporarily downgrading Rust to 1.80 or below, a fix will be out soon.

**Comment by MikolajKolek** [comment]
Fixed in [Toster 1.2.2](https://crates.io/crates/toster/1.2.2).
